name: Gfwlist Decode

on:
  schedule:
    - cron: '0 4 * * *' # 每天凌晨4点触发
  workflow_dispatch: # 手动触发支持

jobs:
  decode-and-update:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出当前仓库
    - name: Checkout this repository
      uses: actions/checkout@v3

    # Step 2: 下载目标文件
    - name: Fetch target file from another repository
      run: |
        curl -o gfwlist64.txt https://raw.githubusercontent.com/gfwlist/gfwlist/refs/heads/master/gfwlist.txt

    # Step 3: Base64 解码
    - name: Decode Base64 file
      run: |
        mkdir -p decoded
        base64 -d gfwlist64.txt > gfwlist.txt

    # Step 4: 提交解码后的文件到当前仓库
    - name: Commit and Push changes
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add gfwlist.txt
        git commit -m "Auto-update decoded file"
        git push origin HEAD
